### ISSUE TITLE
Is there a possible page rotation before applying OCR?

### ISSUE THREAD

**Issue by maxjeblick** [furkanbiten/idl_data#1]
When I use the attached code to visualize the bounding boxes associated with each document, I see some weird examples.
It looks as if the document got dewarped before applying OCR. Yet, I cannot find any associated information thereof in the .json file:

![non_working_example_0038](https://user-images.githubusercontent.com/24281881/178988599-e0121dd0-3c0f-476f-9f84-392588650c6c.png)

Most of the images in the example dataset work fine (although some bboxes seem not perfectly aligned):
![working_example_0050](https://user-images.githubusercontent.com/24281881/178988699-36e04655-86ed-4085-9bd6-a5ec7f01f802.png)

```
import os
import cv2
import os
import numpy as np
import json
import pandas as pd
import matplotlib.pyplot as plt


FILENAME = "ocr_sample/sample/pdfs/ffbb0038/ffbb0038.tif"   # skewd image
#FILENAME = "sample/pdfs/ffbb0050/ffbb0050.tif" 

image = cv2.imread(FILENAME)  # reads first page, only. ffbb0038 and ffbb0050 consist of a single page.
with open(FILENAME.replace("pdfs", "OCR").replace(".tif", ".json")) as f:
    x = json.load(f)

h, w, _ = image.shape

blocks = [b for b in x[1]["Blocks"] if b["BlockType"] == "WORD"]

for block in blocks:
    pts = np.array([[[int(t["X"] * w), int(t["Y"] * h)]
                    for t in block["Geometry"]["Polygon"]]]).astype(np.int32)

    cv2.polylines(image, pts, isClosed=True, color=(255, 0, 0))


plt.rcParams["figure.figsize"] = (12,18)
plt.imshow(image)
```

**Comment by furkanbiten** [comment]
I see that you are using .tif to visualize, however we feed .pdf to extract bounding boxes. And in IDL dataset, pdfs are rectified or edited and while tif is the original documentation. For example, for filename: ffbb0038 this is how tif looks: 
![image](https://user-images.githubusercontent.com/22663927/178996416-9eadb171-4bd0-42d8-9405-dbf0860fed13.png)
While this is how pdf looks:
[ffbb0038.pdf](https://github.com/furkanbiten/idl_data/files/9112306/ffbb0038.pdf)

As you can see, it is already rectified by the IDL people. 

So for the other problem (some bboxes seem not perfectly aligned), i think it should be resolved if you use pdf instead. 

If not, do let me know so that I can investigate more.

**Comment by maxjeblick** [comment]
Thanks for your fast reply!
I didn't notice pdfs are being rectified, already.
