### ISSUE TITLE
Download the OCR data

### ISSUE THREAD

**Issue by rtanaka-lab** [furkanbiten/idl_data#4]
Hi @furkanbiten ,

Thank you for sharing the great dataset! I was trying to download the OCR data via your provided [link](http://datasets.cvc.uab.es/UCSF_IDL/index.txt). However, the index.txt did not contain other than f, g, h, j, and k.tar.gz. 

I was wondering if there is an expected date on when you will release other OCR files such as l, m, and n.tar.gz?

**Comment by furkanbiten** [comment]
Hi @rtanaka-lab,

You are most welcome. 

Unfortunately, there is no expected date on the rest of the data since we ran out of Amazon credits. And, it is very costly otherwise. So, neither I nor my uni has that kind of money.   
However, if someone else run the OCR on the rest of the data, the best I can do is offer hosting in our university server.
